baseURL = 'https://opticfluorine.dev/'
languageCode = 'en-us'
title = 'opticfluorine'
theme = 'hugo-dusk'
copyright = 'Copyright (c) 2025 opticfluorine.'

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)']]

[params]
    math = true
    github = 'opticfluorine'
    discord = 'Mg2jUmePyx'
    bluesky = 'sovereignengine.com'
